version: '3.8'

services:
  flutter-web-app:
    image: ghcr.io/cirruslabs/flutter:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "flutter build web && cp -r build/web/* /usr/share/nginx/html"
    restart: unless-stopped
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /usr/share/nginx/html
    restart: unless-stopped
