name: dnd5e_dm_tools
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_staggered_grid_view: ^0.7.0
  fluttericon: ^2.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  lint: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  petitparser: ^6.0.2
  photo_view: ^0.15.0
  provider: ^6.1.2
  recase: ^4.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/precache/
