services:
  flutter-web-app:
    image: ghcr.io/cirruslabs/flutter:latest
    volumes:
      - .:/app
      - flutter_build:/app/build/web
    working_dir: /app
    command: /bin/sh -c "flutter build web && cp -r build/web/* /usr/share/nginx/html"
    restart: unless-stopped
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - flutter_build:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  flutter_build: