name: dnd5e_dm_tools
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.11
  crypto: ^3.0.6
  equatable: ^2.0.7
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_markdown: ^0.7.7+1
  flutter_staggered_grid_view: ^0.7.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.0
  markdown: ^7.3.0
  path: ^1.9.0
  path_provider: ^2.1.4
  petitparser: ^6.1.0
  recase: ^4.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/img/
      - assets/precache/
